name: qr_mobile_vision
description: "Plugin for reading QR codes using Firebase's Mobile Vision API."
version: 6.0.0
homepage: https://github.com/rmtmckenzie/flutter_qr_mobile_vision

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: '>=3.0.0 <12.0.0'
  native_device_orientation: ^2.0.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.github.rmtmckenzie.qr_mobile_vision
        pluginClass: QrMobileVisionPlugin
      ios:
        pluginClass: QrMobileVisionPlugin
