name: qr_mobile_vision
description: "Plugin for reading QR codes using Firebase's Mobile Vision API."
version: 4.0.1
homepage: https://github.com/rmtmckenzie/flutter_qr_mobile_vision

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.github.rmtmckenzie.qrmobilevision
        pluginClass: QrMobileVisionPlugin
      ios:
        pluginClass: QrMobileVisionPlugin

dependencies:
  flutter:
    sdk: flutter
  native_device_orientation: ^1.0.0
  device_info_plus: '>=3.0.0 <5.0.0'

false_secrets:
  - /example/android/app/google-services.json
  - /example/ios/Runner/GoogleService-Info.plist
